version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: edna
      MYSQL_DATABASE: rentservice
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: rentservice
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
