version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: edna
      MYSQL_DATABASE: rentservice
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build: .
    container_name: rentservice
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer
    depends_on:
      - rabbitmq
      - mysql

volumes:
  mysql-data:
